### ISSUE TITLE
All day events on a given day from the same source should be sorted by alphabetically

### ISSUE THREAD

**Issue by jwalantsoneji** [plusonelabs/calendar-widget#112]
Is it possible to sort events by title?

**Comment by yvolk** [comment]
As implemented in v.3.1 (currently in Beta, see #320) all days events are ordered by the order of corresponding calendars (which may be changed since this app version)
Sorting alphabetically All day events from the same source/calendar looks like an easy and logical thing (we need to avoid randomness anyway...)

Will do this adding one line to org.andstatus.todoagenda.widget.WidgetEntry#compareTo

**Comment by yvolk** [comment]
Done, will be released in v.3.1.2+
