### ISSUE TITLE
Open calendar when "no upcoming events" is tapped

### ISSUE THREAD

**Issue by paul4ig** [plusonelabs/calendar-widget#132]
I have the widget header hidden (another widget on my home screen shows  me the date so I don't want the clutter of duplication). Unfortunately,  that means that I can't easily tap on the widget to get to my Calendar app. 

Could you please add a feature whereby I can just tap on the "no upcoming events" text to access the calendar?

**Comment by yvolk** [comment]
Note: Currently click on "No upcoming events" opens Default Calendar "at today".
Google Calendar forwards this to adding new event for today...

**Comment by eturk1** [comment]
I recall that I used to be able to tap the calendar icon in the upper left to open the calendar app. By finding this request, I just found out I could now tap the date. Maybe I was missing the icon and tapping the top edge of the day. So, how about making the date icon open the calendar, rather than do nothing (at least on my phone right now)?

![Screenshot_20190911-110740](https://user-images.githubusercontent.com/525280/64723335-30719600-d485-11e9-8a5b-e95ad20d944b.png)

**Comment by yvolk** [comment]
@eturk1 This is "Go to today" icon.
In your case it does nothing, because Today is already visible :-)

**Comment by eturk1** [comment]
> @eturk1 This is "Go to today" icon.
> In your case it does nothing, because Today is already visible :-)

sorry, I'm also looking for a fast way to open general calendar app (w/o cal app on home), to look cal over, not a specific day or event. I learned today I can tap a day/date heading in widget to open gen cal. I'd like to tap the icon in upper left.

**Comment by yvolk** [comment]
> I'm also looking for a fast way to open general calendar app (w/o cal app on home), to look cal over, not a specific day or event.

@eturk1 There is such a way also. You need to click a (current) date on the Widget's header. As I see on your screenshot, your widget is too narrow to show even a part od the date. 
So in  order to be able to click that date you need:
a) to make the widget wider OR 
b) use the new option: "Widget header layout"="Two rows layout".
