### ISSUE TITLE
Incorrect time for Russia timezones (MSK)

### ISSUE THREAD

**Issue by antonypavlenko** [plusonelabs/calendar-widget#152]
Hello.
First of all thanks a lot for calendar widget. It is really great and useful.
Last week Russian government changed time one more time. So clocks is switched one hour back.
And all events in calendar widget now 1 hour ahead.
I have tried to check that this is not a android problem, and looks like it isn't: by default there is 2 calendar widgets (as I understand one from Google and one from HTC) and Google widget also have the same problem but HTC widget show events with correct time.
In google calendar by itself all events have correct time zones and in application all events have right start/end time.

![image](https://cloud.githubusercontent.com/assets/2672858/4909084/9f0f9718-6470-11e4-8de3-8f0769f9b969.png)

![image](https://cloud.githubusercontent.com/assets/2672858/4909061/58a79866-6470-11e4-8a75-4b2c570e327e.png)

**Comment by yvolk** [comment]
As a followup to this story: recently I update my Sony XPeria to Android 5 Lollipop, and I noticed that now sometimes even day headers started to show wrong date.
This was solved by updating Joda-Time library to v.2.7

**Comment by yvolk** [comment]
Generally, I see that the problem was not completely solved yet, because it shows, when Time zone table in Joda and in Android firmware differ!
As [Joda-time](https://github.com/dlew/joda-time-android) is updated quicker than Android firmware, we should refactor our code to use Joda Time Zones even to present dates (now we use Android core for this this is why I noticed the problem in my updated xPeria!)

**Comment by yvolk** [comment]
Closing as outdated.
I didn't notice this problem for years already.
