### ISSUE TITLE
Default calendar for new event 

### ISSUE THREAD

**Issue by fredphoesh** [plusonelabs/calendar-widget#155]
Hi, 
By default the widget is choosing a calendar that is not my main calendar.... So it would be good if one could set a default calendar for new events.

**Comment by LawUmp1** [comment]
I updated app last week.  I am now having same problem,  It set outlook as default calendar, rather than the Android Sync Calendar I selected during setup.  Any way to change the default calendar yet?

**Comment by yvolk** [comment]
Default application can be changed by clearing Defaults of current "default" application, see https://github.com/plusonelabs/calendar-widget/issues/238

**Comment by LawUmp1** [comment]
Yes. Already tried that says no default set. Cleared cache memory, uninstalled and reinstalled app., same thing. 


Sent via the Samsung Galaxy Note5, an AT&T 4G LTE smartphone
-------- Original message --------From: Yuri Volkov <notifications@github.com> Date: 4/19/17  1:03 AM  (GMT-06:00) To: plusonelabs/calendar-widget <calendar-widget@noreply.github.com> Cc: LawUmp1 <schaaflaw@gmail.com>, Comment <comment@noreply.github.com> Subject: Re: [plusonelabs/calendar-widget] Default calendar for new event
  (#155) 
Default application can be changed by clearing Defaults of current "default" application, see #238

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/plusonelabs/calendar-widget","title":"plusonelabs/calendar-widget","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/plusonelabs/calendar-widget"}},"updates":{"snippets":[{"icon":"PERSON","message":"@yvolk in #155: Default application can be changed by clearing Defaults of current \"default\" application, see https://github.com/plusonelabs/calendar-widget/issues/238"}],"action":{"name":"View Issue","url":"https://github.com/plusonelabs/calendar-widget/issues/155#issuecomment-295110283"}}}

**Comment by yvolk** [comment]
@LawUmp1 Please take into account that the Calendar-Widget doesn't have a notion of the "Default application". It's Android system, that decides, which Calendar application should be launched as a response to the Calendar Widget's request ( called "Intent" in Android).
So there are two reasons, why Outlook opens without any prompt:
1. It does have some "default" set by Android system.
2. It is the only application on your Device that declares its ability to handle "Intent", generated by the Calendar Widget.

BTW, do you have Google Calendar installed?
