### ISSUE TITLE
Add option to show multiple days event only on the current day

### ISSUE THREAD

**Issue by yvolk** [plusonelabs/calendar-widget#192]
As a User wrote: 
"I'm currently testing your very nice Calendar Widget.
I would like to propose three things however:
Events over multiple days are shown at the first day only or via the setting on every day extra. This is very intrusive in especially with multiple concurrent events.
A better approach would be showing the event only for today, but for every today as long as the event lasts. If the current day lies in the middle of the event show start and end date.
I would suggest adding this as option"

**Comment by mjt543** [comment]
I like having a recurring event show up every day it's scheduled so that each day stands autonomous from another. That's that my calendar app does, and it's what I'd see if I went back to an archaic paper calendar. Otherwise, I risk the adage "out of sight, out of mind" by forgetting to go back to "today" to see those recurring events and event periods. That's how the widget performed before, so that suggested enhancement should be optional, not default.

**Comment by ffes** [comment]
@mjt543 is right. A multiple days event should show up on all days. That should be the default. Otherwise there is no need to put them in the calendar anyway.

**Comment by yvolk** [comment]
As two users commented, they actually need to have a feature that we do have now: 
"Event details" -> "Fill all day events".
