### ISSUE TITLE
Stop Time Zone changes

### ISSUE THREAD

**Issue by gasman32** [plusonelabs/calendar-widget#201]
Could you add a feature like android calendar has to keep event times from changing when travelling to different time zones.  It's frustrating when the times change in the widget because they were made in a different time zone.  My full calendar keeps the times at the original ones so I have 2 times for each calendar event: the widget and the full calendar.
Thanks

**Comment by yvolk** [comment]
This enhancement will have an additional benefit: it will allow to automate testing using different time zones. See #190

**Comment by yvolk** [comment]
I think that interface of this setting may be very simple: just a checkbox.
Title : Fix current time zone
Summary:
1. When off: Timezone name, not fixed.
2. When on: Fixed: Timezone name.
Actual "fix" occurs when a User sets this checkbox.

**Comment by mpost** [comment]
The naming "fix" is very ambiguous. It should describe what is actually happening.

Eg.: "Adjust times to local timezone" with default being "on" (like it is right now).

**Comment by jkufner** [comment]
It is not really "adjusting" nor "fixing". The time of an event is not changed in any way. Only the way how it is displayed is changed.

When a time of an event is not displayed in current (local) time zone, the timezone must be displayed together with the time. Otherwise it shows wrong data.

When traveling by plane, I often have flight represented as an event which has begins in one time zone and ends in another. Lightning (calendar extension for Thunderbird) shows both times in local time zones when event is displayed in calendar view, but when event is edited, each time is shown in time zone specified by user (so the same numbers are on flight ticket and in calendar).

**Comment by yvolk** [comment]
@mpost @jkufner Maybe a word "Lock" is better.
So the title if the checkbox would be: "Lock current Time Zone" ?!
Actually, by "Lock Time Zone" I found the ["Time Zone Lock" feature of the Jorte Calendar](https://www.facebook.com/jorte.net/posts/636216253071174) - this is very close to what we are talking about. But simpler, since we don't need a list of Time Zones to select from - we Lock at current Time Zone.

**Comment by gasman32** [comment]
My calendar program has a box in set up that is labeled "use home time
zone" with an explanation.

**Comment by yvolk** [comment]
The "Time Zone Lock" feature tested to work as expected internally: it is now a part of a test suite, used when we need to replay a list of events in a specific time zone.

**Comment by gasman32** [comment]
Great!

**Comment by yvolk** [comment]
So I propose this implementation of the feature: just a checkbox.
Title : Time Zone Lock
Summary:
1. When off: Unlocked, current zone: Timezone name
2. When on: Locked at Timezone name.
Actual "lock" occurs when a User sets this checkbox.
?!

**Comment by gasman32** [comment]
Perfect!  Thanks.

**Comment by mpost** [comment]
I like the shirt wording. How about we streamline it a little to be more in synch with the other settings? Eg "lock timezone".

**Comment by yvolk** [comment]
@mpost good: "Lock time zone" ("time zone" is used in Android settings. We need to be consistent )

**Comment by mpost** [comment]
@yvolk yeah agreed. "time zone" is correct.

**Comment by yvolk** [comment]
Implemented

**Comment by yvolk** [comment]
To be released in v.1.10.0
