### ISSUE TITLE
Provide static VC/VN for f-droid

### ISSUE THREAD

**Issue by ghost** [plusonelabs/calendar-widget#210]
Hi,

with 1.9.2 a dynamic generated VC/VN was introduced:

https://github.com/plusonelabs/calendar-widget/blob/v1.9.2/app/calendar-widget/build.gradle#L28-L29

This makes it hard to detect new versions at f-droid as discussed here:

https://gitlab.com/fdroid/fdroiddata/issues/322#note_2483736

It would be great if you could provide a static VC/VN again, maybe on a f-droid gradle flavor.

**Comment by okias** [comment]
Pretty please, is possible do something about it?

Calendar Widget is my favorite one.

**Comment by yvolk** [comment]
@ghost @okias  Currently I think that agreeing on some tag names scheme is the simplest way to communicate:
- version name
- version number
- if this is beta or a release

E.g. since 2019 the renamed "ToDo Agenda" widget has such
version names: 3.0.8-523
and version code: 523

We could think about such tag scheme:
\<version name\>-c\<version code\>-release
e.g.: 
3.0.8-523-c523-release

"-c" designates version code...
"-release" - distinguishes from betas, ets. See also #320

?!

**Comment by yvolk** [comment]
I thought about this once again:
Manually typed version numbers belong to the past, and are replaced with version numbers, generated on the fly during app build. This is common for the whole software industry.

This means that in order to sustain F-Droid needs to be updated to handle such cases.

Creation of F-Droid specific build doesn't look reliable: such build will be unreliable, because nobody tests it before F-Droid release. 
Moreover, recently we already found one such problem, specific to F-Droid custom build: #340

**Comment by yvolk** [comment]
@ghost @okias At last I switched to static version name and number. But the problem is that for the last 4 months I simply cannot merge my merge request to F-Droid data repo.
Please help and follow up here: https://github.com/andstatus/todoagenda/issues/31
