### ISSUE TITLE
Tasklist / Todolist

### ISSUE THREAD

**Issue by PushiC** [plusonelabs/calendar-widget#242]
Hi There,

nice app so far, thank you, but there is one thing missing:
I would like to see my ToDoList / TaskList- that i already sync with my other collegues via owncloud at work - to be viewable in your WidGet. Since i updated to Android 6 i have lost one WidGet that was capable of doing that; yours would be a great alternative to that.

thx in advance and big thx for your volunteer.

**Comment by yvolk** [comment]
@PushiC Please see our discussion on using ”events” as ”tasks” https://github.com/plusonelabs/calendar-widget/issues/126
Since implementation of the filter "Show all past events having default color”, I'm using Calendar event color to mark an even as completed. See also https://github.com/plusonelabs/calendar-widget/issues/138

**Comment by yvolk** [comment]
Tasks support added in v.2.1 already.
Though only two concrete "Task providers" are supported now, see #308
