### ISSUE TITLE
It freezing in Huawei mate 10 pro

### ISSUE THREAD

**Issue by eleco2000** [plusonelabs/calendar-widget#279]
It freezing (stop to respond, not read) in Huawei mate 10 pro. Perhaps it has to do with Android oreo.

**Comment by eleco2000** [comment]
Failed to refresh, this is in addition to the above

**Comment by eleco2000** [comment]
when I'm scrolling to the bottom of the list,  most of the times not refresh the list and the message 'reading' stays permanently

**Comment by ykarulin** [comment]
Same here. I have excluded Calendar Widget app from the automated power-saving management but no help.

When it freezes, it keeps showing the past events and doesn't load new events (the "Loading..." line stays there). Clicking on past event opens a calendar though.

![img_20171220_211352](https://user-images.githubusercontent.com/3503973/34224212-cf6b84c4-e5ca-11e7-94c6-917094e7a60c.png)

**Comment by eleco2000** [comment]
Please solve this problem because this calendar widget is the best of it's kind out there

**Comment by yvolk** [comment]
@eleco2000 As the problem is certainly device-specific and doesn't occur on our devices, I think that you need to debug the cause yourself on your devices (granted the source code is opened). You may start from running automated test pack, then investigate actual place of freezing by addition of logging... or try to forward this issue to the device vendor - Huawei.

**Comment by aribeiro2018** [comment]
Hello, I have exactly the same problem on a different phone but also running Android 8 Oreo, I did not have this problem with a previous version of Android. I am not 100% sure that the problem is "device-specific" as yvolk is arguing because on the same phone I have other widgets from 3rd parties working and updating including a different calender widget. The thing is that I do prefer this "calendar widget" over all the others I have seen - it is the best -  so I would much apprecciate if someone could make a contribution to solve this problem described here in this thread.
Thank you

**Comment by xlbk** [comment]
Hello,
Same at my device. After updating to Android 8.0 calendar widget is freezing and only does updates of calendars after restart the device.
So if Logfiles might help, I can provide these.
Best regards

**Comment by mpost** [comment]
Best help would be to debug the widget and see if the calendar content provider is getting called

**Comment by xlbk** [comment]
Thanks for the quick supply. But as I have no idea with software development, I even have no idea how to do that. I'm a design engineer :-) 
I found a thread at xda-developers about same problems with update in many widgets (even news widgets from BBC for example seem to have problems)  after update to Android 8 with Emui 8.0.0
So it might not be a problem with a specific device but with all huawei devices that use the new Emui.
I asked at the huawei support if they know about a specific problem, so let's see what they have to tell. I will keep you updated.

**Comment by xlbk** [comment]
I got feedback from huawei support. There seem to be some issues since update so Android 8 and Emui 8.0.0 with all huawei devices and different calendars (and widgets).
They told me to reinstall the widgets and clear the cache. If this doesn't help, we should wait for the next update. As expected this didn't solve the problem. 
Not very satisfying as the main function of my smartphone (calendar) is not usable any more. I have no idea how long it will take till the next update :-(

**Comment by aribeiro2018** [comment]
What I have found out is that with  Android 8 and Emui 8 there are no problems with the calendar widgets of "Google Calendar" and Huawei's calendar app, they work well. The widgets of other calendar apps have problems, including this "calendar-widget", when then have a window with scrolling of events; if you choose a widget that simply shows events without scrolling it works and refreshs without problem. I guess that if "Google Calendar" widget works without a problem whatsoever it means that this "calendar-widget" also could be changed to work without problems.

**Comment by mpost** [comment]
Thanks for the info. Please let us know when huawei releases an update that adresses the issue.

**Comment by ThomasHaefeli** [comment]
Same problem here.. I have a Huawei P9 Mate with Android 8.0.0. Everything with cache and data deletion, reinstallation, restart, system apps, etc. did not work. Since the update, this problem occurs. First I thought it could also be Nova launcher,.But tests with original Huawei launcher have been negative too. At beginning of this week Google Calendar worked. Now also same problems with Goggle calendar. It seems like the widget freezes after a certain time. The only calendar widget which works fine, is Smooth calendar.. Don't know why.

**Comment by ThomasHaefeli** [comment]
now, all calendar do not work anymore..

**Comment by mcbirne** [comment]
I have the same Problem with my huawei p20pro. Is there any solution or idea?

**Comment by xlbk** [comment]
I'm still waiting for the update from huawei. The problem is reported and I hope huawei is working on this topic. 
The support didn't tell me any date when they plan to release it. 
Sometimes the widget works, sometimes it's freezing.

**Comment by mcbirne** [comment]
I test it. It seams to work if I don't use the scroll function. Is it possible to deactivate the scroll function in the settings? I can't find it.

**Comment by evmin** [comment]
Same issue. Would be nice to fix.

**Comment by sogy** [comment]
Bonjour ,
Même problème sur Honor 7X et depuis la mise à jour vers Android 8.0

Hello,
Same problem on Honor 7X and since the update to Android 8.0

**Comment by eleco2000** [comment]
The developer of the app "Your Calendar widget" which you can find in Google play store, solved the issue. Now I use it in my mate 10 pro and works fine. Sent from mobile device -------- Αρχικό μήνυμα --------Θέμα: Re: [plusonelabs/calendar-widget] It freezing in Huawei mate 10 pro (#279)Από: sogy Προς: plusonelabs/calendar-widget Κοιν.: Elias ,Mention Bonjour ,
Même problème sur Honor 7X et depuis la mise à jour vers Android 8.0
Hello,
Same problem on Honor 7X and since the update to Android 8.0

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/plusonelabs/calendar-widget/issues/279#issuecomment-390960718","url":"https://github.com/plusonelabs/calendar-widget/issues/279#issuecomment-390960718","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/plusonelabs/calendar-widget","title":"plusonelabs/calendar-widget","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/plusonelabs/calendar-widget"}},"updates":{"snippets":[{"icon":"PERSON","message":"@sogy in #279: Bonjour ,\r\nMême problème sur Honor 7X et depuis la mise à jour vers Android 8.0\r\n\r\nHello,\r\nSame problem on Honor 7X and since the update to Android 8.0"}],"action":{"name":"View Issue","url":"https://github.com/plusonelabs/calendar-widget/issues/279#issuecomment-390960718"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [plusonelabs/calendar-widget] It freezing in Huawei mate 10 pro (#279)",
"sections": [
{
"text": "",
"activityTitle": "**sogy**",
"activityImage": "https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png",
"activitySubtitle": "@sogy",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"plusonelabs/calendar-widget\",\n\"issueId\": 279,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"plusonelabs/calendar-widget\",\n\"issueId\": 279\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/plusonelabs/calendar-widget/issues/279#issuecomment-390960718"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 284193218\n}"
}
],
"themeColor": "26292E"
}

**Comment by eleco2000** [comment]
The developer of the app "Your Calendar widget" which you can find in Google play store, solved the issue. Now I use it in my mate 10 pro and works fine.

**Comment by xlbk** [comment]
I also tested the "your calendar widget" and it seems to work fine without any issues on my Huawei P10.
Looks like the developer has found a solution for the freezing problem without any update from Huawei EMUI (which is still not available).
Could Huawei users support the development team of calendars-widget to also find a solution?

**Comment by JPAhnen** [comment]
With the newest update (B145) Huawei finally fixed this bug. No more freezing.

**Comment by eleco2000** [comment]
Wait for three or four days and let see

**Comment by mysmaemi** [comment]
is that bug solution (B145) working? Because I might buy this device soon, hence the question

**Comment by aribeiro2018** [comment]
I have a Huawei P Smart with Android 8 and this calender-widget keeps freezing. I believe it is a problem with this software because all other calender widgets work without a problem whatsoever. I wish they could fix the problem with this calender-widget because it is the best software of its kind out there.
regards

**Comment by JPAhnen** [comment]
@mysmaemi Yeah, it's working fine since the update. The widget updates correctly and doesn't freeze.

@aribeiro2018 I don't know the update cycle of the P Smart, but it is/was a common problem with EMUI 8 and it affects only scrollable widgets.

**Comment by gmazzo** [comment]
Same issue here on my Huawei P10. The firmware is to to date (8.1.0.130 C605) but it's still freezing.

Other widgets have the same issue too
