### ISSUE TITLE
Display current date if there are no events

### ISSUE THREAD

**Issue by tibloop** [plusonelabs/calendar-widget#282]
I created a 1x1 widget with only the events of today. 
I selected the option " display the dates headers for days without event" 
However if there is no event today it only displays " no event comming" when it should still display the date

**Comment by yvolk** [comment]
You mean a Day header. 
It's by design: Day header is shown only if there is at least one event on that date.
Even if you set "Show days without events", such additional day headers are shown only "between" existing (and shown) events.

...But I understand that Calendar apps in some views do show just empty days (or even months...). 

Maybe we simply need to extend the "No upcoming events" message with current date ?!

This is how two possible cases look like in ToDo Agenda v.3.0:
![device-2019-09-28-121438-no-events](https://user-images.githubusercontent.com/207716/65814394-c4fc2800-e1e9-11e9-84ae-c221416dbf19.png)

**Comment by yvolk** [comment]
@tibloop Merging this with more general #265
