### ISSUE TITLE
Add support to display (and complete) Google Tasks

### ISSUE THREAD

**Issue by nickhristov** [plusonelabs/calendar-widget#29]
Using the existing content providers (Astrid, gTasks, etc.)

**Comment by yvolk** [comment]
Seven years forward, some generations of "Google Tasks" changed, but unfortunately I still don't see any documentation on integration with "Google Tasks app", installed on a device. And this is what a widget is about.
Existing documentation tells about integration with remote Google Tasks service:
https://developers.google.com/tasks - but this integration should be done by some "Tasks client" app, not by a "Widget".
Since this summer we support Open Tasks client app. I that integration with Google Tasks would be a good suggestion for that app. Our widget (now called "ToDo Agenda" would show that tasks out of the box...
See #308

**Comment by jimfum** [comment]
Me too would greatly enjoy Google Tasks integration to have both calendar and task events in a nice widget as yours. For tasks the client app I use is Tasks: Astrid To-Do List Clone (https://github.com/tasks) which I'm happy with. As the source code is available it should be possible to integrate if there's enough interest.

**Comment by yvolk** [comment]
@jimfum Aha, so you mean that Astrid To-Do List Clone (https://github.com/tasks) is integrated with Google Tasks, and so we could try to integrate our widget with it?!

Interesting. I only don't see any info if data from this Astrid app can be accessed by our widget on an Android device...

**Comment by jimfum** [comment]
Thanks for a quick reply. That's right. Astrid integrates with Google Tasks and also has its own widget (just tasks, no calendar). As the source code is available, we should be able to access Astrid content from your ToDo Agenda widget I"d presume.

I'm no Java developer but rather .NET. Will try to find time for this, could be an interesting challenge ;) Plus as you wrote, it may not require much of coding but rather configuring...

**Comment by yvolk** [comment]
@jimfum 
> As the source code is available, we should be able to access Astrid content from your ToDo Agenda widget I'd presume

No, this could only help us understand if such possibility exists... Integration with another app means communicating with that app using channels that that app provides.

But of course in a case of an enhancement need at Astrid side we could suggest a change to it (PR)

**Comment by jimfum** [comment]
Thanks @yvolk for explaining. I'll dig into it as an educational exercise.

**Comment by yvolk** [comment]
The feature will be implemented in https://github.com/andstatus/todoagenda/issues/2

**Comment by plusonelabs** [comment]
Von meinem iPad gesendet
