### ISSUE TITLE
Refresh button when "No upcoming events" displayed.

### ISSUE THREAD

**Issue by KAndrsn** [plusonelabs/calendar-widget#294]
The widget will randomly display "No upcoming events".  This is not true.  To get my calendars back, I have to disable/re-enable a calendar in the settings.  It would just be nice to have a button on the widget to refresh/re-sync the widget with the calendars.

**Comment by yvolk** [comment]
@KAndrsn  Please check current Beta v.3.0.* It should solve this issue.

Anyway, even in a case of some similar problem you can open "ToDo Agenda" **app** from your Launcher (not a Widget!), select your widget in the config, and then press Home on your device - the widget should be redrawn even if it "Refresh" button didn't work before.

**Comment by yvolk** [comment]
Your issue with "No upcoming events" in v.2.x that requires to re-enable the widget, will not occur in v.3 simply because in v.3. "No upcoming events" is not present on the uninitialised widget.
Now you could see something like in #318, the bug that I have fixed recently, see #320

Unfortunately, when a widget is not initialised (like in your case) there is really no way to have working "refresh button", because even that button needs to be set up for the "Refresh" action - this is Android platform limitation.
