### ISSUE TITLE
Update v3.0.11 to v3.1.6 is breaking again the widget

### ISSUE THREAD

**Issue by MaxXor** [plusonelabs/calendar-widget#353]
After updating Todo Agenda from v3.0.11 to v3.1.6 the widget is broken again. Same procedure as mentioned in the [README.md](https://github.com/plusonelabs/calendar-widget/blob/master/README.md#2019-10-05--v3011-more-colors-and-layout-customizations) needs to be followed again to get it working. Any reason why it's always breaking the widget in the last two updates?

**Comment by yvolk** [comment]
The problem with upgrade may be caused by difference between the widget's layout, cached by your Launcher app, and current actual widget layout.

Yes, I made some widget's layout changes...

Unfortunately, as we noticed, at least some launchers don't even delete data about widgets of uninstalled apps (!). 
This is why even after app uninstall reboot is needed (and may more than one...) to force that "unaware" Launcher to forget outdated widget info...

@MaxXor  You may also try to avoid reinstall, but do reboot(s) only
?!

And don't forget that we do have Backup/Restore now!

**Comment by MaxXor** [comment]
Thanks for the fast reply. First I just rebooted the device which didn't fix the problem, so reboot only didn't work. I'm using the default launcher of LineageOS. Yes, backup & restore worked flawlessly.

**Comment by yvolk** [comment]
@MaxXor BTW, recently we noticed one incompatibility with F-Droid build of the Widget and LineageOS device with default ("Trebuchet") launcher: https://github.com/plusonelabs/calendar-widget/issues/340
And only with that launcher...

**Comment by MaxXor** [comment]
Thanks yes, that's the launcher I'm using (and f-droid build too). The widget was still shown in the list of widgets though... anyways it's working now after following the reinstall + reboot instructions.
