### ISSUE TITLE
Option to hide tasks with no dates

### ISSUE THREAD

**Issue by gtbuchanan** [plusonelabs/calendar-widget#358]
Currently, all Tasks with no start or due date seem to be displayed under today's date. I have dozens of tasks without dates, as I consider them generally as "I must complete this at some time in the future, but not necessarily today or ASAP." I'd expect to use my Tasks app to assign deadlines when they can be determined. Since some folks might rely on the current functionality, it would be great to have an option in the settings to "Hide Tasks Without Dates".

**Comment by yvolk** [comment]
@gtbuchanan I agree that tasks (or even any _events_) without dates are of a special kind and we should be able to hide them or maybe show only such events in some separate view/widget...

BTW could you look and take part in the related discussion on tasks filtering: https://github.com/plusonelabs/calendar-widget/issues/356

**Comment by yvolk** [comment]
@gtbuchanan We will implement this special filtering as a part of #356, please see the discussion.

**Comment by ekalin** [comment]
I'd create another task list for the tasks that I don't want shown in the widget, and deselect this task list in the widget settings.

If I wanted to see a task, I'd move it to the main list (which is displayed), possibly adding a date if necessary.

---

As long as this hiding of tasks with no dates is optional, I'd see no problem in adding the feature. But were it my widget, I'd be reluctant to do that because too many options make the code complex and hard to test, and also too many options might make it harder for users -- too many settings to go through, hard to find a specific setting, doubts about what each option does, etc.

**Comment by gtbuchanan** [comment]
@ekalin I've considered the separate task list workaround but it would double the amount of lists, which is both more complex and verbose than necessary. I have "Personal" and shared "Family" lists so that would require two new lists in addition to a new list for each family member personal calendar. I'd also have to teach everyone to add these types of tasks to the new calendar instead.

I understand the concern of increased code complexity, but I believe this situation warrants it to avoid pushing complexity to the end-users. I'm in agreement with the proposed solutions in #356.
