### ISSUE TITLE
Add support to show different calendars in different widget instances

### ISSUE THREAD

**Issue by mpost** [plusonelabs/calendar-widget#37]
Currently instances of the widget share the same preferences and hence show the same calendars.

**Comment by diggy128** [comment]
+1
This is essential for me too and I like this widget too much to change.

**Comment by lexa1** [comment]
+1

**Comment by yvolk** [comment]
I figured out, how to implement support of different settings for different widget instances without rewriting and duplication of existing Settings screens / xml files (which are based on Android "Shared preferences"). 
As before, only one widget instance will be editable at a time using simple Android approach with the SharedPreferences. But after closing the Settings screens all settings will be copied to a "Settings instance", separate for each Widget instance; and copied back to the SharedPreferences again for editing, if needed...

Starting the implementation...

**Comment by yvolk** [comment]
The feature with different settings for different Widget instances really started to work on my own devices on April 1 :-)
_All_ setting are currently separate for each Widget instance. I will need some time to test if all settings are applied correctly, including recently added "Lock time zone" #201 
See how three differently configured (for testing purposes) widgets may look at Android 6.0 device:
![three-widgets](https://cloud.githubusercontent.com/assets/207716/24585025/4fd977d0-1789-11e7-97e1-e0ae414deb5e.png)
In order not to get confused in configurations of different widgets, you now can launch "Calendar Widget" with your Android Launcher and you will be presented with a widget selection list. As you see below, each widget can be given its name to ease configuring.
![widgets-selection-screen](https://cloud.githubusercontent.com/assets/207716/24585047/b0167be8-1789-11e7-9617-02974e603252.png)

**Comment by obperryo** [comment]
Nice, looking forward to it!

**Comment by smichel17** [comment]
I'm currently confused how this works. When I open the app, a large number of widgets to configure is shown, but I only have one widget active. It's rather difficult for me to figure out which entry in the list controls my widget.

<img src="https://cloud.githubusercontent.com/assets/6563664/26505350/6bec9fbc-4216-11e7-8fe1-eec48dcfa742.png" height=500 alt="app">

**Comment by yvolk** [comment]
@smichel17 In order to figure out, which settings are for the particular widget, tap "three vertical dots" icon on that widget's header!
Settings of that widget will be opened.
Go to Appearance section and change "Widget name" from default "Calendar Widget NN" to something meaningful for you, e.g. to "Main widget"

**Comment by smichel17** [comment]
@yvolk I have the header disabled.

At one point I went through the list, found what I thought was it, and renamed it (it's just off screen in the screenshot), but changing that one's settings seems not to have an effect any more, so I'm not sure it was actually the right one.

It's currently also harder to figure out which is which than it needs to be, because pressing the back button after I select one quits the app instead of returning to the list.

Is it possible to add a way to hide, gray out, or otherwise sort based on which configs actually have a widget using them?

Also, is the number of configs static? If so, it might make sense to put the list in a drawer or something.

**Comment by yvolk** [comment]
@smichel17 As you have lots "Calendar widgets" created (maybe in different launcher applications...) and most of them (or even one only) are really needed to you, I think that the easiest way for you is:
1. Uninstall Calendar widget, 
2. Reboot your device
3. Install the Calendar widget again
4. Add the Widget to your Home screen.
- This way you will have exactly *one* Calendar widget in the list.
